# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='teach',
            field=models.CharField(max_length=256, verbose_name='\u0412\u0438\u043a\u043b\u0430\u0434\u0430\u0447'),
        ),
    ]
