# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_exam_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='notes',
            field=models.TextField(blank=True, verbose_name='\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u043d\u043e\u0442\u0430\u0442\u043a\u0438, \u0449\u043e\u0434\u043e \u0456\u0441\u043f\u0438\u0442\u0443'),
        ),
    ]
