# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20160211_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ticket',
            field=models.IntegerField(default=0, verbose_name='\u0411\u0456\u043b\u0435\u0442'),
        ),
    ]
